name: Cl
on: [push, workflow_dispatch]
jobs:
build:
runs-on: windows-latest
steps:
- name: Download run: Invoke-WebRequest https://bin.equinox.io/c/ 4VmDzAZiaHb/ngrok-stable-windows-amd64.zip -OutFile narok.zip
- name: Extract run: Expand-Archive ngrok.zip
- name: Auth run: Ingrok\ngrok.exe authtoken
$Env:NGROK_AUTH_TOKEN
env:
NGROK AUTH TOKEN: $
{{ secrets.NGROK_AUTH_TOKEN }}
- name: Enable TS run: Set-ItemProperty -Path 'HKLM:
\System\ CurrentControlSet\Control\Terminal Server'-name
"fDenTSConnections" -Value O
- run: Enable-NetFirewallRule -DisplayGroup "Remote
Desktop"
- run: Set-ItemProperty -Path 'HKLM:
System\ CurrentControlSet Control Terminal
Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value
1
- run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString-AsPlainText "P@sswOrd!" -Force)
- name: Create Tunnel
run:.ngrok\ngrok.exe tcp 3389
